services:
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    container_name: nuxt-client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: dockerfile.server
    container_name: nest-server
    env_file:
      - server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

volumes:
  db_data:
