FROM node:18

WORKDIR /app

RUN curl -sSL https://github.com/jwilder/dockerize/releases/download/v0.9.1/dockerize-linux-amd64-v0.9.1.tar.gz -o dockerize.tar.gz && \
    tar -xzvf dockerize.tar.gz && \
    mv dockerize /usr/local/bin/ && \
    rm dockerize.tar.gz

COPY ./package*.json .

RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 8000

CMD ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "30s", "npm", "run", "start"]
